### ISSUE TITLE
Nonstandard encoding

### ISSUE THREAD

**Issue by eth-r** [multiformats/cs-multibase#4]
The encoding used by this library in bases 2, 8 and 10 is non-standard and incompatible with other implementations, conflicting with the intent of the multibase project

**Comment by tabrath** [comment]
Ok, I will look into this. When this was implemented there was no specification or other implementations for reference, so I hope there will be some test vectors all implementation can test against soon.

**Comment by eth-r** [comment]
I proposed a set of test vectors in https://github.com/multiformats/multibase/issues/24 to help standardize the libraries

**Comment by tabrath** [comment]
Nice, that's just what I need. I'll start working on this asap. Thank you.

**Comment by tabrath** [comment]
@eth-r Released a new version of the library, it's completely rewritten and passes all your test vectors now and fixes multiformats/multibase#34.
